version: "3.9"

services:
#  redis:
#    image: redis
#    container_name: 'demo_app_redis'
#    command: redis-server
#    ports:
#      - '6379:6379'
  adminer:
    image: adminer
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=RootRocketData
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=RocketDataTestDB
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    environment:
      - POSTGRES_USER=RootRocketData
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=RocketDataTestDB
    depends_on:
      - db
#      - redis
#  celery:
#    build: .
#    container_name: 'demo_app_celery'
#    command: celery -A server worker -b
#    volumes:
#      - .:/code
#    links:
#      - redis
#    depends_on:
#      - web
#      - redis